"""fix relationship constraint

Revision ID: 53273ede58ef
Revises: 3c67dca44f4d
Create Date: 2023-08-23 14:45:25.995274

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '53273ede58ef'
down_revision = '3c67dca44f4d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('relationships', schema=None) as batch_op:
        batch_op.drop_constraint('uq_relationships_from_many_id', type_='unique')
        batch_op.create_unique_constraint(batch_op.f('uq_relationships_from_many_id'), ['from_many_id', 'to_one_id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('relationships', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('uq_relationships_from_many_id'), type_='unique')
        batch_op.create_unique_constraint('uq_relationships_from_many_id', ['from_many_id'])

    # ### end Alembic commands ###
