"""add unique constraint to UserSchema

Revision ID: a736cb8dc87a
Revises: b47ec2f2e64c
Create Date: 2023-08-18 19:23:49.585597

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a736cb8dc87a'
down_revision = 'b47ec2f2e64c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user_schemas', schema=None) as batch_op:
        batch_op.create_unique_constraint(batch_op.f('uq_user_schemas_user_id'), ['user_id', 'schema_id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user_schemas', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('uq_user_schemas_user_id'), type_='unique')

    # ### end Alembic commands ###
